InfMapTopic: "/mock_map"

OdomTopic: "/visual_slam/odom"

TargetTopic: "/goal"

PointCloudUsePCD: true

PointCloudPath: "/config/indoor_map.pcd"

OutlierThreshold: 1

DilateRadius: 0.15

GridResolution: 0.05

R3Bound:
  [-7.0, 7.0, -4.5, 5.0, 0.0, 4.0]
  # [xmin, xmax, ymin, ymax, zmin, zmax]

LocalBoxHalfWidth: 3.0

ExpectedHeight: [0.4, 4.0]

Astar_weight: 0.0

CorridorPath: "/config/test_corridor.txt"


SetPos: 
  [
# split-S
    0.820, 2.467, 0.520,
    4.808, 1.010, 3.000,
    4.908, 1.010, 3.000,
    5.052, 0.875, 0.63,
  
    0.924, 2.271, 1.340,
    -1.267, 2.213, 1.520,
# powerloop
    -6.673, 1.497, 0.600,
    -4.589, 1.405, 2.900,
    -3.689, 1.405, 2.900,
    -3.589, 1.405, 2.900,
    -2.834, 1.254, 0.620,
    -6.821, 1.506, 0.680,

# barry roll
    -6.504, -1.946, 2.060,
    -2.463, -0.171, 2.780,
    -2.263, -0.171, 2.780,
    -2.063, -0.171, 2.780,

    1.000, 2.000, 1.000, 
    6.070, 1.130, 1.000, 
  ]

# key attitude
# x+:[ 1,  0,  0]
# x-:[-1,  0,  0]
# y+:[ 0,  1,  0]
# y-:[ 0, -1,  0]
# z+:[ 0,  0,  1] stable
# z-:[ 0,  0, -1]

SetAtt: 
  [ # x, y, z, flag,

    0,   0,   1,    0,
    0,   1,   0,    0,
    0,   0,  -1,    1,
    0,   0,   1,    0,

    0,   0,   1,    0,
    0,   0,   1,    0,

    0,   0,   1,    0,
    1,   0,   0,    0,
    0,   0,  -1,    1,
   -1,   0,   0,    0,
    0,   0,   1,    0,
    0,   0,   1,    0,

    0,   0,   1,    0,
    0,   1,   0,    0,
    0,   0,  -1,    1,
    0,  -1,   0,    0,
    0,   0,   1,    0,
    0,   0,   1,    0,
  ]