InfMapTopic: "/mock_map"

OdomTopic: "/visual_slam/odom"

TargetTopic: "/goal"

PointCloudUsePCD: true

PointCloudPath: "/config/outdoor_map.pcd"

OutlierThreshold: 1

DilateRadius: 0.3

GridResolution: 0.2

R3Bound:
  [-18.0, 81.0, -24.0, 46.0, -1.0, 15.0]
  # [xmin, xmax, ymin, ymax, zmin, zmax]

LocalBoxHalfWidth: 5.0

ExpectedHeight: [0.5, 20]

Astar_weight: 0.0

CorridorPath: "/config/test_corridor.txt"

SetPos: 
  [
      20.0, 8.0, 1.0,
      44.0, 12.0, 2.1,

      56.0, 10.0, 2.1,
      52.0, 11.0, 11.0,
      50.0, 12.0, 12.0,
      47.0, 13.0, 11.0,
      45.4, 15.7, 2.1, 

      56.0, 7.0, 1.0, 

      56.7, -5.7, 11.5, 
      59.7, -5.7, 11.5, 
      61.7, -9.8, 3.5, 
      53.1, -8.8, 1.0, 

      42.1, 4.6, 1.5,
      28.6, 8.2, 6.0,

      23.0, 15.0, 9.6,
      22.5, 15.5, 10.6,
      17.5, 17.5, 3.0,
      8.0, 16.5, 1.0,
      0.0, 0.0, 1.0,
  ]

# x+:[ 1,  0,  0]
# x-:[-1,  0,  0]
# y+:[ 0,  1,  0]
# y-:[ 0, -1,  0]
# z+:[ 0,  0,  1] stable
# z-:[ 0,  0, -1]

SetAtt: 
  [ # x, y, z, flag,
    0,   0,   1,    0,
    0,   0,   1,    0,

    0,   0,   1,    0,
   -1,   0,   0,    0,
    0,   0,  -1,    1,
    1,   0,   0,    0,
    0,   0,   1,    0,

    0,   0,   1,    0,
    1,   0,   0,    0,
    0,   0,  -1,    1,
  #  -1,   0,   0,    0,
    0,   0,   1,    0,
    0,   0,   1,    0,

    0,   0,   1,    0,
    0,   0,   1,    0,
    # 0,   0,   1,    0,

    0,   1,   0,    0,
    0,   0,  -1,    1,
    0,   0,   1,    0,
    0,   0,   1,    0,
    0,   0,   1,    0,
  ]