
InfMapTopic: "/mock_map"

OdomTopic: "/visual_slam/odom"

TargetTopic: "/goal"

PointCloudUsePCD: false

PointCloudPath: "/not_use_in_unity_sim"

OutlierThreshold: 1

DilateRadius: 0.2

GridResolution: 0.10

R3Bound: # not_use_in_unity_sim
  [-2.0, 25.0, -10.0, 10.0, -1.0, 6.0]
  # [xmin, xmax, ymin, ymax, zmin, zmax]

LocalBoxHalfWidth: 3.0

ExpectedHeight: [0.3, 8]

Astar_weight: 0.0

CorridorPath: "/config/test_corridor.txt"

# not use in this mode
SetPos: 
  [
     5,    3,   2,
     1,    2,   2,
     2,    5,   2,
  ]

SetAtt: 
  [
    0,   0,   1,    0,
    0,   0,   1,    0,
    0,   0,   1,    0,
  ]